### ISSUE TITLE
modification méthode de recherche

### ISSUE THREAD

**Issue by ghost** [HeptanomeDeLExtreme/TP-WebSem#3]
_Dans le fichier main.py :_

Modifier la méthode searchOnTheWeb pour qu'on puisse effectuer des requêtes de plusieurs mots.

**Comment by Omadzu** [comment]
Finalement, ce n'est pas le problème, il faut trouver pourquoi les requêtes de plusieurs mots (type jean marie le pen) ne fonctionnent pas. Pas besoin de diviser la requête en plusieurs mots puis de faire la recherche sur chacun de ces mots.
