### ISSUE TITLE
Jaccard

### ISSUE THREAD

**Issue by ghost** [HeptanomeDeLExtreme/TP-WebSem#4]
_Dans le fichier jaccard2.py :_
- Modifier la méthode createGroups pour qu'il nomme avec un sens logique les groupes. Par exemple en se basant sur les URI.
- Faire en sorte d'avoir des groupements cohérents. Genre les coefs de jaccard sont entre 0 et 0.1, du coup c'est dur d'avoir des groupements cohérents. Poser la question aux profs pour savoir comment faire

**Comment by Omadzu** [comment]
Ajouter un nom d'URI aux groupes OK
